name: NPM PUBLISH
permissions:
    id-token: write
on:
    release:
        types: [ published ]
defaults:
    run:
        shell: bash
jobs:
    publish:
        name: 'Publish: firebase-realtime-database registry'
        runs-on: ubuntu-latest
        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v4
            - name: SETUP NODE
              uses: actions/setup-node@v4
              with:
                node-version: latest
                registry-url: 'https://registry.npmjs.org'
            - name: SETUP BUN
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest
            - name: INSTALL DEPENDENCIES
              run: bun install
            - name: BUILD
              run: bun build.ts
            - name: PUBLISH TO NPMJS
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm publish --provenance --access=public
